<?php

/**
 * TIPTAP_sauth — South Africa defaults only.
 * Tanzania settings belong in the TAPTAP tz project.
 */
return [
    'market' => env('TIPTAP_MARKET', 'za'),

    'currency_symbol' => env('TIPTAP_CURRENCY_SYMBOL', 'R'),

    'currency_code' => env('TIPTAP_CURRENCY_CODE', 'ZAR'),

    'country_code' => env('TIPTAP_COUNTRY_CODE', '27'),

    'payment_gateway' => env('TIPTAP_PAYMENT_GATEWAY', 'PayFast'),

    'admin_live_poll_seconds' => (int) env('ADMIN_LIVE_POLL_SECONDS', 30),

    'phone_local_example' => env('TIPTAP_PHONE_EXAMPLE', '082 123 4567'),

    'phone_international_prefix' => env('TIPTAP_PHONE_PREFIX', '+27'),

    'default_whatsapp_bot_number' => env('TIPTAP_WHATSAPP_BOT_NUMBER', '27821234567'),

    'admin_setting_groups' => [
        'system_name' => 'general',
        'support_email' => 'general',
        'commission_rate' => 'financial',
        'min_withdrawal' => 'financial',
        'demo_push' => 'payments',
        'whatsapp_bot_number' => 'api',
        'webhook_secret' => 'api',
    ],

    /*
    |--------------------------------------------------------------------------
    | Public landing page — offices & social (TipTap Africa)
    |--------------------------------------------------------------------------
    */
    'company' => [
        'offices' => [
            'tz' => [
                'name' => 'Tanzania',
                'flag' => 'tz',
                'city' => 'Dar es Salaam, Kinondoni',
                'lines' => [
                    'Tanzanite Park',
                    '13th Floor',
                ],
            ],
            'za' => [
                'name' => 'South Africa',
                'flag' => 'za',
                'city' => 'Lonehill, Gauteng',
                'lines' => [
                    '16 Capricorn Road',
                    'Lonehill, 2062',
                ],
            ],
        ],
        'whatsapp_url' => env('TIPTAP_WHATSAPP_URL', 'https://wa.me/27821234567'),
        'social' => [
            'facebook' => env('TIPTAP_SOCIAL_FACEBOOK'),
            'instagram' => env('TIPTAP_SOCIAL_INSTAGRAM'),
            'x' => env('TIPTAP_SOCIAL_X'),
            'linkedin' => env('TIPTAP_SOCIAL_LINKEDIN'),
            'tiktok' => env('TIPTAP_SOCIAL_TIKTOK'),
            'youtube' => env('TIPTAP_SOCIAL_YOUTUBE'),
        ],
    ],

    'landing' => [
        'sections' => [
            'hero' => 'Hero section',
            'demo' => 'Video demo & live Rafiki',
            'nurture' => 'Nurture CTAs & lead magnet',
            'contact' => 'Contact & offices',
            'social' => 'Social media & WhatsApp',
            'cta' => 'Bottom call to action',
            'seo' => 'SEO & schema markup',
            'footer' => 'Footer',
        ],
        'fields' => [
            'hero_live_badge' => ['nullable', 'string', 'max:50'],
            'hero_badge_text' => ['nullable', 'string', 'max:200'],
            'hero_title_line1' => ['nullable', 'string', 'max:120'],
            'hero_title_line2' => ['nullable', 'string', 'max:120'],
            'hero_description' => ['nullable', 'string', 'max:1000'],
            'hero_rafiki_intro' => ['nullable', 'string', 'max:300'],
            'hero_rafiki_meaning' => ['nullable', 'string', 'max:300'],
            'hero_cta_primary' => ['nullable', 'string', 'max:80'],
            'hero_cta_secondary' => ['nullable', 'string', 'max:80'],
            'demo_title' => ['nullable', 'string', 'max:160'],
            'demo_subtitle' => ['nullable', 'string', 'max:300'],
            'demo_video_url' => ['nullable', 'url', 'max:500'],
            'demo_try_rafiki_label' => ['nullable', 'string', 'max:80'],
            'demo_try_rafiki_message' => ['nullable', 'string', 'max:120'],
            'nurture_book_demo_label' => ['nullable', 'string', 'max:80'],
            'nurture_book_demo_calendly_url' => ['nullable', 'url', 'max:500'],
            'nurture_book_demo_whatsapp_message' => ['nullable', 'string', 'max:300'],
            'nurture_chat_with_us_label' => ['nullable', 'string', 'max:80'],
            'nurture_lead_magnet_title' => ['nullable', 'string', 'max:160'],
            'nurture_lead_magnet_subtitle' => ['nullable', 'string', 'max:500'],
            'nurture_lead_magnet_button' => ['nullable', 'string', 'max:80'],
            'nurture_lead_magnet_success' => ['nullable', 'string', 'max:300'],
            'seo_title' => ['nullable', 'string', 'max:160'],
            'seo_description' => ['nullable', 'string', 'max:320'],
            'seo_keywords' => ['nullable', 'string', 'max:500'],
            'contact_label' => ['nullable', 'string', 'max:80'],
            'contact_title' => ['nullable', 'string', 'max:160'],
            'contact_description' => ['nullable', 'string', 'max:500'],
            'contact_social_title' => ['nullable', 'string', 'max:120'],
            'contact_social_description' => ['nullable', 'string', 'max:500'],
            'office_tz_name' => ['nullable', 'string', 'max:80'],
            'office_tz_city' => ['nullable', 'string', 'max:160'],
            'office_tz_line1' => ['nullable', 'string', 'max:160'],
            'office_tz_line2' => ['nullable', 'string', 'max:160'],
            'office_za_name' => ['nullable', 'string', 'max:80'],
            'office_za_city' => ['nullable', 'string', 'max:160'],
            'office_za_line1' => ['nullable', 'string', 'max:160'],
            'office_za_line2' => ['nullable', 'string', 'max:160'],
            'social_facebook' => ['nullable', 'url', 'max:500'],
            'social_instagram' => ['nullable', 'url', 'max:500'],
            'social_x' => ['nullable', 'url', 'max:500'],
            'social_linkedin' => ['nullable', 'url', 'max:500'],
            'social_tiktok' => ['nullable', 'url', 'max:500'],
            'social_youtube' => ['nullable', 'url', 'max:500'],
            'whatsapp_url' => ['nullable', 'url', 'max:500'],
            'cta_title' => ['nullable', 'string', 'max:160'],
            'cta_description' => ['nullable', 'string', 'max:500'],
            'cta_button' => ['nullable', 'string', 'max:80'],
            'footer_tagline' => ['nullable', 'string', 'max:300'],
        ],
        'trust' => [
            'headline' => 'Trusted by restaurants across South Africa',
            'metrics' => [
                ['value' => '50+', 'label' => 'Live restaurants', 'icon' => 'store'],
                ['value' => '10k+', 'label' => 'Orders processed', 'icon' => 'receipt'],
            ],
            'partners_label' => 'Secured payments via',
            'partners' => [
                ['name' => 'PayFast', 'logo' => 'images/partners/payfast.svg', 'width' => 96],
                ['name' => 'Visa', 'logo' => 'images/partners/visa.svg', 'width' => 64],
                ['name' => 'Mastercard', 'logo' => 'images/partners/mastercard.svg', 'width' => 48],
            ],
            'featured_in_label' => 'As featured in',
            'featured_in' => [],
            'stats_headline' => 'Trusted by leading restaurants across South Africa for faster ordering and payments',
            'stats' => [
                ['value' => '24/7', 'label' => 'Bot always on'],
                ['value' => '4.9★', 'label' => 'Manager rating'],
                ['value' => 'Instant', 'label' => 'Payment settlement'],
                ['value' => 'Zero', 'label' => 'Apps for guests'],
            ],
        ],
        'partners' => [
            'eyebrow' => 'Payment integrations',
            'title' => 'Powered by trusted payment partners',
            'subtitle' => 'Card, Instant EFT, and mobile payments are processed through PayFast — South Africa\'s leading payment gateway — with Visa and Mastercard acceptance.',
            'footnote' => 'Regulated payment rails your finance team and guests already trust.',
            'groups' => [
                [
                    'label' => 'Payment gateway',
                    'items' => [
                        ['name' => 'PayFast', 'logo' => 'images/partners/payfast.svg', 'width' => 108],
                    ],
                ],
                [
                    'label' => 'Cards & EFT',
                    'items' => [
                        ['name' => 'Visa', 'logo' => 'images/partners/visa.svg', 'width' => 72],
                        ['name' => 'Mastercard', 'logo' => 'images/partners/mastercard.svg', 'width' => 56],
                        ['name' => 'Instant EFT', 'logo' => 'images/partners/instant-eft.svg', 'width' => 112],
                    ],
                ],
            ],
        ],
        'nurture' => [
            'book_demo_label' => 'Book a 20-minute demo',
            'book_demo_whatsapp_message' => 'Hi, I would like to book a 20-minute TipTap demo.',
            'chat_with_us_label' => 'Chat with us',
            'cta_secondary_hint' => 'Not ready to sign up? Book a quick walkthrough or chat with our team on WhatsApp.',
            'lead_magnet_eyebrow' => 'Free guide',
            'lead_magnet_title' => 'Get our restaurant efficiency guide — free',
            'lead_magnet_subtitle' => 'Practical tips on QR ordering, WhatsApp guest flows, and faster table turns — written for restaurants in South Africa.',
            'lead_magnet_button' => 'Send me the guide',
            'lead_magnet_success' => 'Thanks! We will email your guide shortly.',
            'lead_magnet_privacy' => 'No spam. Unsubscribe anytime.',
        ],
        'seo' => [
            'html_lang' => 'en-ZA',
            'locale' => 'en_ZA',
            'geo_region' => 'ZA',
            'geo_place_name' => 'South Africa',
            'og_type' => 'website',
            'twitter_card' => 'summary_large_image',
            'og_image' => 'images/logo.png',
        ],
        'faq' => [
            'chat_label' => 'Still have questions?',
            'chat_cta' => 'Chat with us on WhatsApp',
            'items' => [
                [
                    'question' => 'What is TipTap?',
                    'answer' => 'TipTap is a restaurant operating system built for South Africa: QR table ordering, TipTap Rafiki on WhatsApp, card and EFT payments, a kitchen display, and live manager dashboards — all in one platform.',
                ],
                [
                    'question' => 'Do customers need to download an app?',
                    'answer' => 'No. Guests scan a QR code at the table and order through WhatsApp — the app they already use every day. No downloads, no new accounts, no friction.',
                ],
                [
                    'question' => 'Which payment methods are supported?',
                    'answer' => 'Card, Instant EFT, and mobile payments via PayFast. Bills, tips, and settlements are tracked in real time on your dashboard.',
                ],
                [
                    'question' => 'What happens if the internet goes down?',
                    'answer' => 'Orders already sent to the kitchen display stay visible on screen. If connectivity drops briefly, TipTap queues messages and syncs when the connection returns. Your team can also take manual orders and reconcile once back online.',
                ],
                [
                    'question' => 'How long does setup take?',
                    'answer' => 'Most restaurants go live in under a day. Upload your menu, assign table QR codes, connect PayFast, and invite your team — our onboarding guide walks you through each step.',
                ],
                [
                    'question' => 'How do I train my staff?',
                    'answer' => 'Waiters need only their TIPTAP-W code and a two-minute walkthrough. Kitchen staff use a simple display screen. We provide quick-start guides and WhatsApp support during your first week.',
                ],
                [
                    'question' => 'Is my restaurant data safe?',
                    'answer' => 'Yes. Data is encrypted in transit, hosted on secure infrastructure, and access is role-based — managers, waiters, and admins only see what they need. Payments are processed by regulated partners such as PayFast.',
                ],
                [
                    'question' => 'Can I use TipTap for multiple branches?',
                    'answer' => 'Yes. Enterprise plans support multiple venues under one account with separate menus, staff, and reporting per branch — ideal for groups and franchises.',
                ],
                [
                    'question' => 'Can waiters register separately?',
                    'answer' => 'Yes. Each waiter receives a unique TIPTAP-W registration code and links to your venue through the manager dashboard. They can track their own tips and orders.',
                ],
                [
                    'question' => 'How does the kitchen receive orders?',
                    'answer' => 'Confirmed orders appear instantly on the kitchen display screen, grouped by table and course. Staff mark items as prepared so front-of-house knows when to serve.',
                ],
                [
                    'question' => 'How does tipping work?',
                    'answer' => 'Guests can add a tip when paying through WhatsApp. Tips are attributed to the assigned waiter and visible on manager and waiter dashboards for transparent payout tracking.',
                ],
                [
                    'question' => 'Is there a free trial?',
                    'answer' => 'Yes. Start with a 14-day free trial — no card required. Test QR ordering, TipTap Rafiki, and payments with real tables before choosing a plan.',
                ],
            ],
        ],
        'testimonials' => [
            'title' => 'What managers are saying',
            'items' => [
                [
                    'quote' => 'We cut order time by 40% in the first week. Customers order from the table on WhatsApp and PayFast settlements hit our account the same day.',
                    'highlight' => '40% faster orders',
                    'name' => 'Thabo Nkosi',
                    'role' => 'Operations Manager',
                    'restaurant' => 'Ember and Oak Steakhouse',
                    'city' => 'Johannesburg',
                    'photo' => null,
                ],
                [
                    'quote' => 'Card and EFT payments through PayFast removed the end-of-night cash chaos. Staff tips are transparent and managers finally have one dashboard.',
                    'highlight' => null,
                    'name' => 'Lerato Mokoena',
                    'role' => 'Owner',
                    'restaurant' => 'Atlantic Table',
                    'city' => 'Cape Town',
                    'photo' => null,
                ],
                [
                    'quote' => 'The kitchen screen keeps our brunch rush under control. Orders from WhatsApp appear instantly and the pass never gets backed up.',
                    'highlight' => null,
                    'name' => 'David van Wyk',
                    'role' => 'Head Chef',
                    'restaurant' => 'Green Valley Eatery',
                    'city' => 'Pretoria',
                    'photo' => null,
                ],
            ],
        ],
        'features' => [
            'subtitle' => 'QR tables, TipTap Rafiki, payments, kitchen screen, and manager dashboard — one beautiful platform.',
            'rafiki_card_body' => 'Rafiki means "friend" — your venue\'s always-on WhatsApp assistant for menu browsing, orders, bills, and tips.',
        ],
        'demo' => [
            'title' => 'Watch Rafiki handle a full guest journey',
            'subtitle' => 'Scan QR, chat with Rafiki, place an order, and pay with card or instant EFT — all in under 90 seconds.',
            'walkthrough_label' => 'Interactive preview',
            'video_poster' => 'images/demo/rafiki-demo-poster.svg',
            'try_rafiki_label' => 'Try Rafiki now',
            'try_rafiki_message' => 'Hi',
            'try_rafiki_hint' => 'Opens WhatsApp with our live demo bot. Say Hi to explore the menu — no signup required.',
            'steps' => [
                ['icon' => 'qr-code', 'title' => 'Scan table QR', 'caption' => 'Guest scans the code on the table — no app download.'],
                ['icon' => 'messages-square', 'title' => 'Chat with Rafiki', 'caption' => 'Browse the menu and build an order inside WhatsApp.'],
                ['icon' => 'utensils-crossed', 'title' => 'Order hits the kitchen', 'caption' => 'Staff see the order instantly on kitchen display.'],
                ['icon' => 'banknote', 'title' => 'Pay with PayFast', 'caption' => 'Card, Visa, Mastercard, or instant EFT — bill and tip in one flow.'],
            ],
        ],
        'pricing' => [
            'title' => 'Simple plans, clear value',
            'billing_monthly' => 'Monthly',
            'billing_annual' => 'Annual',
            'annual_promo' => 'Pay 10 months, get 2 free',
            'annual_savings' => 'Save ~17%',
            'business_slug' => 'business',
            'enterprise_slug' => 'enterprise',
            'business_anchor' => 'Less than the cost of one hardware POS terminal per year.',
            'enterprise_from_label' => 'Starts from',
            'enterprise_note' => 'Custom onboarding for groups and franchises',
        ],
        'defaults' => [
            'hero_live_badge' => 'Live',
            'hero_badge_text' => 'TipTap Rafiki · WhatsApp · QR · PayFast',
            'hero_title_line1' => 'Order, pay, and tip',
            'hero_title_line2' => 'from a WhatsApp chat',
            'hero_description' => 'Guests scan a QR code, place orders, leave reviews, and pay with mobile money or bank — no app, no queues, no hassle.',
            'hero_rafiki_intro' => 'Meet Rafiki — your restaurant\'s WhatsApp friend, always on, always ready.',
            'hero_rafiki_meaning' => 'Rafiki means "friend" — TipTap\'s always-on WhatsApp assistant for orders, payments, and guest care.',
            'hero_cta_primary' => 'Start free trial',
            'hero_cta_secondary' => 'See Rafiki in action',
            'demo_title' => 'Watch Rafiki handle a full guest journey',
            'demo_subtitle' => 'Scan QR, chat with Rafiki, place an order, and pay with card or instant EFT — all in under 90 seconds.',
            'demo_video_url' => env('TIPTAP_DEMO_VIDEO_URL', ''),
            'demo_try_rafiki_label' => 'Try Rafiki now',
            'demo_try_rafiki_message' => 'Hi',
            'nurture_book_demo_label' => 'Book a 20-minute demo',
            'nurture_book_demo_calendly_url' => env('TIPTAP_BOOK_DEMO_CALENDLY_URL', ''),
            'nurture_book_demo_whatsapp_message' => 'Hi, I would like to book a 20-minute TipTap demo.',
            'nurture_chat_with_us_label' => 'Chat with us',
            'nurture_lead_magnet_title' => 'Get our restaurant efficiency guide — free',
            'nurture_lead_magnet_subtitle' => 'Practical tips on QR ordering, WhatsApp guest flows, and faster table turns — written for restaurants in South Africa.',
            'nurture_lead_magnet_button' => 'Send me the guide',
            'nurture_lead_magnet_success' => 'Thanks! We will email your guide shortly.',
            'seo_title' => 'TipTap — QR & WhatsApp Restaurant Ordering in South Africa | PayFast & Cards',
            'seo_description' => 'TipTap helps restaurants in South Africa accept QR and WhatsApp orders, settle card and Instant EFT via PayFast, and run kitchen display plus live analytics. Meet TipTap Rafiki — free trial.',
            'seo_keywords' => 'restaurant ordering South Africa, WhatsApp menu, QR ordering Cape Town, PayFast, TipTap Rafiki, kitchen display, Johannesburg restaurants',
            'contact_label' => 'TipTap Africa',
            'contact_title' => 'Where we operate',
            'contact_description' => 'TipTap is managed from our offices in Tanzania and South Africa. Reach us at either location or connect on social media.',
            'contact_social_title' => 'Follow TipTap Africa',
            'contact_social_description' => 'Connect with us on social media for product updates, restaurant success stories, and support.',
            'office_tz_name' => 'Tanzania',
            'office_tz_city' => 'Dar es Salaam, Kinondoni',
            'office_tz_line1' => 'Tanzanite Park',
            'office_tz_line2' => '13th Floor',
            'office_za_name' => 'South Africa',
            'office_za_city' => 'Lonehill, Gauteng',
            'office_za_line1' => '16 Capricorn Road',
            'office_za_line2' => 'Lonehill, 2062',
            'social_facebook' => env('TIPTAP_SOCIAL_FACEBOOK', ''),
            'social_instagram' => env('TIPTAP_SOCIAL_INSTAGRAM', ''),
            'social_x' => env('TIPTAP_SOCIAL_X', ''),
            'social_linkedin' => env('TIPTAP_SOCIAL_LINKEDIN', ''),
            'social_tiktok' => env('TIPTAP_SOCIAL_TIKTOK', ''),
            'social_youtube' => env('TIPTAP_SOCIAL_YOUTUBE', ''),
            'whatsapp_url' => env('TIPTAP_WHATSAPP_URL', 'https://wa.me/27821234567'),
            'cta_title' => 'Upgrade your restaurant today',
            'cta_description' => 'Join venues already using TipTap Rafiki, QR ordering, and instant mobile payments.',
            'cta_button' => 'Create free account',
            'footer_tagline' => 'The operating system for modern dining. Built with care in South Africa.',
        ],
    ],
];
